# VulnTrace SQL Injection Training Lab
# Maintainer: vulntrace@gmail.com
# Compose Version: 3.8

version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - mysql
    container_name: php5_sql_vuln_web
    volumes:
      - ./access_logs:/var/log/apache2
    labels:
      maintainer: "vulntrace@gmail.com"

  mysql:
    image: mysql:5.7
    container_name: mysql_sql_vuln
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
